apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.PROM.name }}
  labels:
    service: {{ .Values.PROM.name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  ports:
    - name: prom-http
      port: {{ .Values.PROM.port }}
      targetPort: 9090
  selector:
    service: {{ .Values.PROM.name }}
