apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-http
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ .Values.MENDHAK.name }}
              servicePort: {{ .Values.MENDHAK.port }}
          - path: /metric
            pathType: Prefix
            backend:
              serviceName: {{ .Values.PROM.name }}
              servicePort: {{ .Values.PROM.port }}